# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 12:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DmtcUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(editable=False)),
                ('updated_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('place', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('mobile_no', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_admin', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(editable=False)),
                ('updated_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('mobile_no', models.CharField(max_length=12)),
                ('gst_no', models.CharField(max_length=15)),
                ('office_no', models.CharField(max_length=12)),
                ('company', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('bank', models.CharField(max_length=255)),
                ('bank_account', models.CharField(max_length=20)),
                ('user_count', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dmtcuser',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant'),
        ),
        migrations.AddField(
            model_name='dmtcuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
