# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20171101_2051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500, null=True)),
                ('mobile_no', models.CharField(max_length=12)),
                ('office_no', models.CharField(max_length=12, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('gst_no', models.CharField(max_length=15, null=True)),
                ('pan_no', models.CharField(max_length=10, null=True)),
                ('credit_limit', models.IntegerField()),
                ('total_credit', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuyerBanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('bank', models.CharField(max_length=255)),
                ('bank_account', models.CharField(max_length=20)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Buyer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuyerChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile_no', models.CharField(max_length=12, null=True)),
                ('office_no', models.CharField(max_length=12, null=True)),
                ('gst_no', models.CharField(max_length=15, null=True)),
                ('pan_no', models.CharField(max_length=10, null=True)),
                ('commission_percentage', models.FloatField(default=0)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Buyer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuyerChildBanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('bank', models.CharField(max_length=255)),
                ('bank_account', models.CharField(max_length=20)),
                ('buyer_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.BuyerChild')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=500, null=True)),
                ('place', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('commission_percentage', models.FloatField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubTenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('place', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500, null=True)),
                ('mobile_no', models.CharField(max_length=12)),
                ('gst_no', models.CharField(max_length=15, null=True)),
                ('office_no', models.CharField(max_length=12, null=True)),
                ('company', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('user_count', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubTenantBanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('bank', models.CharField(max_length=255, null=True)),
                ('bank_account', models.CharField(max_length=20, null=True)),
                ('sub_tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SubTenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500, null=True)),
                ('mobile_no', models.CharField(max_length=12)),
                ('office_no', models.CharField(max_length=12, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('gst_no', models.CharField(max_length=15, null=True)),
                ('pan_no', models.CharField(max_length=10, null=True)),
                ('commission_percentage', models.FloatField()),
                ('credit_limit', models.IntegerField()),
                ('total_credit', models.IntegerField()),
                ('sub_tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.SubTenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierBanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('bank', models.CharField(max_length=255)),
                ('bank_account', models.CharField(max_length=20)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500, null=True)),
                ('mobile_no', models.CharField(max_length=12)),
                ('office_no', models.CharField(max_length=12, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('gst_no', models.CharField(max_length=15, null=True)),
                ('pan_no', models.CharField(max_length=10, null=True)),
                ('commission_percentage', models.FloatField()),
                ('sub_tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.SubTenant')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierChildBanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('bank', models.CharField(max_length=255)),
                ('bank_account', models.CharField(max_length=20)),
                ('supplier_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.SupplierChild')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('quality', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('sort_no', models.CharField(max_length=255)),
                ('packing', models.IntegerField()),
                ('size', models.IntegerField()),
                ('rate', models.FloatField()),
                ('cuts', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('sub_tenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.SubTenant')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Supplier')),
                ('supplier_child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.SupplierChild')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TenantBanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('bank', models.CharField(max_length=255, null=True)),
                ('bank_account', models.CharField(max_length=20, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='bank_account',
        ),
        migrations.AlterField(
            model_name='dmtcuser',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='dmtcuser',
            name='mobile_no',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='address',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='gst_no',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tenant',
            name='office_no',
            field=models.CharField(max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='tenantbanking',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant'),
        ),
        migrations.AddField(
            model_name='supplierinventory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant'),
        ),
        migrations.AddField(
            model_name='supplierchild',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant'),
        ),
        migrations.AddField(
            model_name='subtenant',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant'),
        ),
        migrations.AddField(
            model_name='salesman',
            name='sub_tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.SubTenant'),
        ),
        migrations.AddField(
            model_name='salesman',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant'),
        ),
        migrations.AddField(
            model_name='buyerchild',
            name='sub_tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.SubTenant'),
        ),
        migrations.AddField(
            model_name='buyerchild',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='sub_tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.SubTenant'),
        ),
        migrations.AddField(
            model_name='buyer',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant'),
        ),
        migrations.AddField(
            model_name='dmtcuser',
            name='sub_tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.SubTenant'),
        ),
    ]
