# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 12:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indents', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(editable=False)),
                ('updated_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('buyer_name', models.CharField(max_length=255)),
                ('supplier_name', models.CharField(max_length=255)),
                ('indent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indents.Indents')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(editable=False)),
                ('updated_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('bill_date', models.DateTimeField(default=datetime.datetime(2017, 11, 1, 17, 48, 11, 896379))),
                ('quality', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('sort_no', models.CharField(max_length=255)),
                ('bales', models.IntegerField()),
                ('cuts', models.IntegerField()),
                ('size', models.IntegerField()),
                ('rate', models.FloatField()),
                ('dispatch_no', models.CharField(max_length=255)),
                ('dispatch_date', models.DateTimeField()),
                ('lorry_no', models.CharField(max_length=255)),
                ('lorry_date', models.DateTimeField()),
                ('lorry_fare', models.FloatField()),
                ('lorry_from', models.CharField(max_length=255)),
                ('lorry_to', models.CharField(max_length=255)),
                ('courier_no', models.CharField(max_length=255)),
                ('courier_date', models.DateTimeField()),
                ('bill_sent', models.BooleanField()),
                ('bill_sent_date', models.BooleanField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Bill')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indents.Transport')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(editable=False)),
                ('updated_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('quality', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('is_short', models.BooleanField()),
                ('sort_no', models.CharField(max_length=255)),
                ('bales', models.IntegerField()),
                ('size', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('bill_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Bill')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
