# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='billorder',
            name='bill_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 1, 20, 51, 22, 295516)),
        ),
        migrations.AlterField(
            model_name='billorder',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='billorder',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='discrepancy',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='discrepancy',
            name='updated_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
