# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_auto_20171101_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billorder',
            name='bill_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
