# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indents', '0006_auto_20171117_0021'),
        ('users', '0004_auto_20171117_0021'),
        ('billing', '0005_auto_20171105_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='prepared_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.DmtcUser'),
        ),
        migrations.AddField(
            model_name='billorder',
            name='indent_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indents.IndentOrder'),
        ),
        migrations.AddField(
            model_name='billorder',
            name='remarks',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='discrepancy',
            name='bill_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='billing.BillOrder'),
        ),
        migrations.AddField(
            model_name='discrepancy',
            name='prepared_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.DmtcUser'),
        ),
        migrations.AddField(
            model_name='discrepancy',
            name='remarks',
            field=models.CharField(default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='billorder',
            name='bill_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='billorder',
            name='bill_sent_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='billorder',
            name='courier_date',
            field=models.DateTimeField(null=True),
        ),
    ]
