# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 12:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(editable=False)),
                ('updated_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('mobile_no', models.CharField(max_length=12)),
                ('office_no', models.CharField(max_length=12)),
                ('gst_no', models.CharField(max_length=15)),
                ('pan_no', models.CharField(max_length=10)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BuyerBanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(editable=False)),
                ('updated_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254)),
                ('bank', models.CharField(max_length=255)),
                ('bank_account', models.CharField(max_length=20)),
                ('credit_limit', models.IntegerField()),
                ('total_credit', models.IntegerField()),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indents.Buyer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConfirmationOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(editable=False)),
                ('updated_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('packing', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('quality', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('sort_no', models.CharField(max_length=255)),
                ('bales', models.IntegerField()),
                ('size', models.IntegerField()),
                ('rate', models.FloatField()),
                ('remarks', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndentOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(editable=False)),
                ('updated_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('bales', models.IntegerField()),
                ('remarks', models.CharField(max_length=1000)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Indents',
            fields=[
                ('created_date', models.DateTimeField(editable=False)),
                ('updated_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('indent_no', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('indent_date', models.DateTimeField(default=datetime.datetime(2017, 11, 1, 17, 48, 11, 890953))),
                ('bank_name', models.CharField(max_length=255)),
                ('cash_discount', models.FloatField()),
                ('scheme', models.CharField(max_length=255)),
                ('payment_day', models.IntegerField()),
                ('credit_day', models.IntegerField()),
                ('interest_rate', models.FloatField()),
                ('pending', models.BooleanField()),
                ('indent_from', models.CharField(max_length=255)),
                ('indent_to', models.CharField(max_length=255)),
                ('export_to', models.CharField(max_length=255)),
                ('remarks', models.CharField(max_length=1000)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indents.Buyer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Salesman',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(editable=False)),
                ('updated_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=500)),
                ('place', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('commission_percentage', models.FloatField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(editable=False)),
                ('updated_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('mobile_no', models.CharField(max_length=12)),
                ('office_no', models.CharField(max_length=12)),
                ('gst_no', models.CharField(max_length=15)),
                ('pan_no', models.CharField(max_length=10)),
                ('commission_percentage', models.FloatField()),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierBanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(editable=False)),
                ('updated_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254)),
                ('bank', models.CharField(max_length=255)),
                ('bank_account', models.CharField(max_length=20)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indents.Supplier')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierChild',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(editable=False)),
                ('updated_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('place', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('mobile_no', models.CharField(max_length=12)),
                ('office_no', models.CharField(max_length=12)),
                ('gst_no', models.CharField(max_length=15)),
                ('pan_no', models.CharField(max_length=10)),
                ('commission_percentage', models.FloatField()),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indents.Supplier')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierChildBanking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(editable=False)),
                ('updated_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254)),
                ('bank', models.CharField(max_length=255)),
                ('bank_account', models.CharField(max_length=20)),
                ('supplier_child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indents.SupplierChild')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SupplierInventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(editable=False)),
                ('updated_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('quality', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
                ('sort_no', models.CharField(max_length=255)),
                ('packing', models.IntegerField()),
                ('size', models.IntegerField()),
                ('rate', models.FloatField()),
                ('cuts', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indents.Supplier')),
                ('supplier_child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indents.SupplierChild')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(editable=False)),
                ('updated_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('transport_name', models.CharField(max_length=255)),
                ('mobile_no', models.CharField(max_length=12)),
                ('office_no', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='indents',
            name='salesman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indents.Salesman'),
        ),
        migrations.AddField(
            model_name='indents',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indents.Supplier'),
        ),
        migrations.AddField(
            model_name='indents',
            name='supplier_child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='indents.SupplierChild'),
        ),
        migrations.AddField(
            model_name='indents',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant'),
        ),
        migrations.AddField(
            model_name='indents',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indents.Transport'),
        ),
        migrations.AddField(
            model_name='indentorder',
            name='indent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indents.Indents'),
        ),
        migrations.AddField(
            model_name='indentorder',
            name='supplier_inventory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indents.SupplierInventory'),
        ),
        migrations.AddField(
            model_name='indentorder',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant'),
        ),
        migrations.AddField(
            model_name='confirmationorder',
            name='indent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indents.Indents'),
        ),
        migrations.AddField(
            model_name='confirmationorder',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant'),
        ),
    ]
