# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 12:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CnoteDnote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(editable=False)),
                ('updated_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('note_no', models.CharField(max_length=255)),
                ('bank', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 11, 1, 17, 48, 11, 900847))),
                ('dd_no', models.CharField(max_length=6)),
                ('cheque_no', models.CharField(max_length=6)),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
                ('remarks', models.CharField(max_length=1000)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Bill')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DraftSlip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(editable=False)),
                ('updated_date', models.DateTimeField()),
                ('active', models.BooleanField(default=True)),
                ('bank', models.CharField(max_length=255)),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 11, 1, 17, 48, 11, 899694))),
                ('dd_no', models.CharField(max_length=6)),
                ('cheque_no', models.CharField(max_length=6)),
                ('amount', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
                ('remarks', models.CharField(max_length=1000)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.Bill')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Tenant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
