# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 15:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_auto_20171101_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cnotednote',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 1, 20, 52, 58, 265299)),
        ),
        migrations.AlterField(
            model_name='draftslip',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 1, 20, 52, 58, 263770)),
        ),
    ]
