# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 15:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20171105_0952'),
        ('accounting', '0004_auto_20171101_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnotednote',
            name='sub_tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.SubTenant'),
        ),
        migrations.AddField(
            model_name='draftslip',
            name='sub_tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.SubTenant'),
        ),
    ]
