# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-17 06:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20171117_0021'),
        ('accounting', '0005_auto_20171105_0952'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cnotednote',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='draftslip',
            name='date',
        ),
        migrations.AddField(
            model_name='cnotednote',
            name='prepared_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.DmtcUser'),
        ),
        migrations.AddField(
            model_name='draftslip',
            name='cash_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='draftslip',
            name='prepared_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.DmtcUser'),
        ),
        migrations.AddField(
            model_name='draftslip',
            name='supplier_banking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.SupplierBanking'),
        ),
        migrations.AddField(
            model_name='draftslip',
            name='supplier_child_banking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.SupplierChildBanking'),
        ),
    ]
